# Generated by Django 6.1.1 on 2026-09-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('is_voltooid', models.BooleanField(default=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
